# Generated by Django 6.0.2 on 2026-03-05 22:35

import villas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Cover image for the villa (shown on listing and detail).', null=True, upload_to=villas.models.villa_thumbnail_path),
        ),
    ]
