# Generated by Django 6.0.2 on 2026-03-28 01:14

import django.db.models.deletion
import villas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0002_add_villa_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_entry',
            field=models.BooleanField(default=False, help_text='If checked, this room is where the tour starts (only one per villa recommended).'),
        ),
        migrations.AddField(
            model_name='room',
            name='photosphere',
            field=models.ImageField(blank=True, help_text='Equirectangular 360° panorama for the virtual tour (Street View style).', null=True, upload_to=villas.models.room_photosphere_path),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='is_360',
            field=models.BooleanField(default=False, help_text='Legacy: prefer Room photosphere for tour. Use for optional flat gallery only.'),
        ),
        migrations.CreateModel(
            name='RoomHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaw', models.FloatField(help_text='Horizontal angle in degrees (Pannellum yaw).')),
                ('pitch', models.FloatField(help_text='Vertical angle in degrees (Pannellum pitch).')),
                ('label', models.CharField(blank=True, help_text='Optional label on the hotspot.', max_length=200)),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots_out', to='villas.room')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots_in', to='villas.room')),
            ],
            options={
                'ordering': ['from_room_id', 'pk'],
            },
        ),
    ]
