# Generated by Django 5.2.5 on 2026-04-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0004_alter_room_id_alter_roomhotspot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='bathroom_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of bathrooms / toilets (WCs).'),
        ),
        migrations.AddField(
            model_name='villa',
            name='bedroom_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of bedrooms (for listings and filters).'),
        ),
        migrations.AddField(
            model_name='villa',
            name='city',
            field=models.CharField(blank=True, help_text='City (used for search and filters on the public list).', max_length=120),
        ),
        migrations.AddField(
            model_name='villa',
            name='has_garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='villa',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Display price (e.g. per night). Leave empty if not shown.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='property_type',
            field=models.CharField(choices=[('villa', 'Villa'), ('apartment', 'Apartment'), ('house', 'House'), ('townhouse', 'Townhouse'), ('land', 'Land'), ('commercial', 'Commercial'), ('other', 'Other')], default='villa', max_length=20),
        ),
        migrations.AddField(
            model_name='villa',
            name='zone',
            field=models.CharField(blank=True, help_text='Neighborhood, district, or zone.', max_length=120),
        ),
    ]
