"""
Django settings for villa_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
    load_dotenv(BASE_DIR / "villa_project" / ".env")
except ImportError:
    pass


def _normalize_email_password(raw: str) -> str:
    if not raw:
        return ""
    p = raw.strip().strip('"').strip("'")
    if p.startswith("\ufeff"):
        p = p.lstrip("\ufeff")
    return p.strip()


def _read_email_host_password_from_dotenv_files() -> str:
    """
    Read EMAIL_HOST_PASSWORD=... directly from .env files.

    On Windows, python-dotenv occasionally misses values (encoding/BOM), and editors
    sometimes save .env in UTF-16; utf-8-sig covers UTF-8 BOM; UTF-16 fails fast.
    """
    for path in (BASE_DIR / ".env", BASE_DIR / "villa_project" / ".env"):
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8-sig")
        except UnicodeDecodeError:
            try:
                text = path.read_text(encoding="utf-16")
            except OSError:
                continue
        except OSError:
            continue
        for raw in text.splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            if key.strip().upper() != "EMAIL_HOST_PASSWORD":
                continue
            p = _normalize_email_password(value)
            if p:
                return p
    return ""


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h!n%&70po(!8a28j1627k683*^9-lvbm!!*imk3mg*^5ybnc7q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'villas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'villa_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'villa_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

# Email (booking notifications)
# -----------------------------------------------------------------------------
# Real SMTP is used when a password is set via ANY of:
#   1) .env in project root:  EMAIL_HOST_PASSWORD=your-app-password
#   2) Environment variable EMAIL_HOST_PASSWORD (PowerShell: $env:EMAIL_HOST_PASSWORD="...")
#   3) File email_password.txt in project root (first line only) — add to .gitignore
#
# Gmail: create an App Password (Google Account → Security → 2-Step → App passwords).
# DEFAULT_FROM_EMAIL and EMAIL_HOST_USER should match the Gmail address you send as.
#
# If no password is set, the console backend is used (email text only in the terminal).
# -----------------------------------------------------------------------------
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "erink1ked@gmail.com")
ADMINS = [("Erin", "erink1ked@gmail.com")]
BOOKING_NOTIFICATION_EMAILS = ["erink1ked@gmail.com"]

_email_pw = _normalize_email_password(os.environ.get("EMAIL_HOST_PASSWORD", ""))
if not _email_pw:
    _email_pw = _read_email_host_password_from_dotenv_files()
if not _email_pw:
    for _pw_path in (
        BASE_DIR / "email_password.txt",
        BASE_DIR / "villa_project" / "email_password.txt",
    ):
        if _pw_path.is_file():
            try:
                line = _pw_path.read_text(encoding="utf-8").splitlines()[0]
                _email_pw = _normalize_email_password(line)
                break
            except OSError:
                pass

if _email_pw:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", DEFAULT_FROM_EMAIL)
    EMAIL_HOST_PASSWORD = _email_pw
    EMAIL_TIMEOUT = 20
    if EMAIL_PORT == 465:
        EMAIL_USE_TLS = False
        EMAIL_USE_SSL = True
    else:
        EMAIL_USE_TLS = True
        EMAIL_USE_SSL = False
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
